# Generated by Django 4.0.6 on 2022-08-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0003_inmuebles_m2_terreno'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmuebles',
            name='numero_est',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
