# Generated by Django 4.0.6 on 2022-08-03 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0004_inmuebles_numero_est'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='id_comuna',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.comuna'),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='m7_python.region'),
        ),
    ]
