# Generated by Django 4.0.6 on 2022-08-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m7_python', '0005_alter_inmuebles_id_comuna_alter_inmuebles_id_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_banos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inmuebles',
            name='numero_hab',
            field=models.IntegerField(default=0),
        ),
    ]
