# Generated by Django 4.0.6 on 2022-08-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('m7_python', '0007_alter_inmuebles_nombre_inmueble'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m7_python.inmuebles')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
